name: Build and Release Assets
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Write API key to .env.production
      - name: Write VITE_IMGBB_API_KEY to .env.production
        run: echo "VITE_IMGBB_API_KEY=${{ secrets.VITE_IMGBB_API_KEY }}" > .env.production

      # Step 5: Build Extension
      - name: Build Extension
        run: npm run build:extension

      # Step 6: Build Website
      - name: Build Website
        run: npm run build:website

      # Step 7: Zip artifacts
      - name: Zip Artifacts
        run: |
          zip -r extension.zip ./extension
          zip -r website.zip ./dist

      # Step 8: Upload artifacts to the release that triggered this workflow
      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            extension.zip
            website.zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
